// Re-export from new domain location for backwards compatibility
export {
  renderLocalizedDate,
  renderExtendedDate,
  renderCompetitionTime,
  renderDateTimeComposite,
  renderCompetitionScore,
  renderCompactCapacity,
  renderCompetitionPhase,
  renderCompetitionStatus,
  renderPercentageValue,
  renderPossessionPercentage,
  renderGoalMargin,
  renderTeamPerformanceRecord,
  renderRelativeTimestamp,
  // Legacy names
  formatMatchDate,
  formatLongDate,
  formatMatchTime,
  formatDateTime,
  formatScore,
  formatCapacity,
  formatPhase,
  formatMatchStatus,
  formatPercentage,
  formatPossession,
  formatGoalDifference,
  formatTeamRecord,
  formatRelativeTime
} from '@domain/presentation/FormattersRegistry';
